/*6. Create an array of objects representing cars in a dealership. 
Each object has the following properties: id, make, model, and price. 
Write a React component where you can create an array of cars and return 
an unordered list of cars, 
where each list item displays the car's make, model, and price. */
const cars = [
  {
    id: 3292,
    brandName: "Hyundai",
    brandSlug: "hyundai",
    name: "Verna",
    slug: "verna",
    avgRating: 4.7,
    reviewCount: 109,
    variantName: "SX Opt Turbo",
    variantSlug: "sx-opt-turbo",
    variantPrice: "15.99 Lakh",
    minPrice: "10.90 Lakh",
    minComparePrice: 0,
    maxPrice: "17.38 Lakh",
    priceRange: "10.90 - 17.38 Lakh",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Verna/8703/1679389180298/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Mar 21, 2023",
    expiredAt: "Mar 15, 2047",
    isSponsored: false,
    variants: [
      {
        name: "EX",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "10.90 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_EX.htm",
        variantCTAText: "Verna EX",
        variantCTATitle: "Hyundai Verna EX",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "S",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "11.96 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_S.htm",
        variantCTAText: "Verna S",
        variantCTATitle: "Hyundai Verna S",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "12.98 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX.htm",
        variantCTAText: "Verna SX",
        variantCTATitle: "Hyundai Verna SX",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX IVT",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "14.23 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX_IVT.htm",
        variantCTAText: "Verna SX IVT",
        variantCTATitle: "Hyundai Verna SX IVT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX Opt",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "14.66 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX_Opt.htm",
        variantCTAText: "Verna SX Opt",
        variantCTATitle: "Hyundai Verna SX Opt",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX Turbo",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "14.84 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX_Turbo.htm",
        variantCTAText: "Verna SX Turbo",
        variantCTATitle: "Hyundai Verna SX Turbo",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX Opt Turbo",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "15.99 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX_Opt_Turbo.htm",
        variantCTAText: "Verna SX Opt Turbo",
        variantCTATitle: "Hyundai Verna SX Opt Turbo",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX Turbo DCT",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "16.08 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX_Turbo_DCT.htm",
        variantCTAText: "Verna SX Turbo DCT",
        variantCTATitle: "Hyundai Verna SX Turbo DCT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX Opt IVT",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "16.20 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX_Opt_IVT.htm",
        variantCTAText: "Verna SX Opt IVT",
        variantCTATitle: "Hyundai Verna SX Opt IVT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "SX Opt Turbo DCT",
        vehicleType: "Sedans",
        fuelType: "Petrol",
        price: "17.38 Lakh",
        launchedAt: "March 21, 2023",
        url: "/overview/Hyundai_Verna/Hyundai_Verna_SX_Opt_Turbo_DCT.htm",
        variantCTAText: "Verna SX Opt Turbo DCT",
        variantCTATitle: "Hyundai Verna SX Opt Turbo DCT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/hyundai/verna",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Verna/8703/1679389180298/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Hyundai Verna",
    vehicleTypeCount: 0,
    noOfVariants: 10,
    engine: "1482 cc",
    mileage: "20.0 kmpl",
    seatingCapacity: "5 Seats",
    fuelType: "Petrol",
    transmissionType: "Manual",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Hyundai",
      modelName: "Hyundai Verna",
      carVariantId: "Hyundai Verna SX Opt Turbo",
      modelId: 3292,
      modelUrl: "/hyundai/verna",
      modelPriceURL: "/hyundai/verna/price-in-new-delhi",
      priceRnge: "10lakh-15lakh,15lakh-20lakh",
      bodyType: "Sedans",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "verna",
      dcbFormHeading: "View Personalized Offers On Hyundai Verna",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Hyundai Verna",
      cityId: "49",
      orpTitle: "Hyundai Verna On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9751",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: true,
      isDealerConnect: true,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Hyundai/Verna/8703/1679389180298/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Mar 21, 2023 12:00:00 AM",
    isVariant: false,
    gorpDto: {
      brandName: "Hyundai",
      modelName: "Hyundai Verna",
      carVariantId: "Hyundai Verna SX Opt Turbo",
      modelUrl: "/hyundai/verna",
      modelPriceURL: "/hyundai/verna/price-in-new-delhi",
      priceRnge: "10lakh-15lakh,15lakh-20lakh",
      ctaText: "Get on Road Price",
      modelSlug: "verna",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 3276,
    brandName: "Mercedes-Benz",
    brandSlug: "mercedes-benz",
    name: "AMG G 63",
    slug: "amg-g-63",
    avgRating: 4.5,
    reviewCount: 97,
    variantName: "4MATIC",
    variantSlug: "4matic",
    variantPrice: "3.30 Cr",
    minPrice: "3.30 Cr",
    minComparePrice: 0,
    maxPrice: "3.30 Cr",
    priceRange: "3.30 Cr",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mercedes-Benz/AMG-G-63/9737/1679289361128/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Mar 17, 2023",
    expiredAt: "Mar 17, 2046",
    isSponsored: false,
    variants: [
      {
        name: "4MATIC",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "3.30 Cr",
        launchedAt: "March 17, 2023",
        url:
          "/overview/Mercedes-Benz_AMG_G_63/Mercedes-Benz_AMG_G_63_4MATIC.htm",
        variantCTAText: "AMG G 63 4MATIC",
        variantCTATitle: "Mercedes-Benz AMG G 63 4MATIC",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/mercedes-benz/amg-g-63",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mercedes-Benz/AMG-G-63/9737/1679289361128/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Mercedes-Benz AMG G 63",
    vehicleTypeCount: 0,
    noOfVariants: 1,
    engine: "3982 cc",
    mileage: "",
    seatingCapacity: "5 Seats",
    fuelType: "Petrol",
    transmissionType: "Automatic",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Mercedes-Benz",
      modelName: "Mercedes-Benz AMG G 63",
      carVariantId: "Mercedes-Benz AMG G 63 4MATIC",
      modelId: 3276,
      modelUrl: "/mercedes-benz/amg-g-63",
      modelPriceURL: "/mercedes-benz/amg-g-63/price-in-new-delhi",
      priceRnge: "1+crore",
      bodyType: "SUV",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "amg-g-63",
      dcbFormHeading: "View Personalized Offers On Mercedes-Benz AMG G 63",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Mercedes-Benz AMG G 63",
      cityId: "49",
      orpTitle: "Mercedes-Benz AMG G 63 On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9737",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: false,
      isDealerConnect: false,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mercedes-Benz/AMG-G-63/9737/1679289361128/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Mar 17, 2023 4:00:00 PM",
    isVariant: false,
    cardIconTagList: [
      {
        text: "Facelift",
        defaultKey: false,
        brandId: 0,
        keyFeatureAvailable: false,
        showRs: false,
        iconClass: "icon-facelift",
        rightFlag: true,
        minPriceRange: 0,
        maxPriceRange: 0,
        isNctFilterOn: false,
        showFillButton: false
      }
    ],
    gorpDto: {
      brandName: "Mercedes-Benz",
      modelName: "Mercedes-Benz AMG G 63",
      carVariantId: "Mercedes-Benz AMG G 63 4MATIC",
      modelUrl: "/mercedes-benz/amg-g-63",
      modelPriceURL: "/mercedes-benz/amg-g-63/price-in-new-delhi",
      priceRnge: "1+crore",
      ctaText: "Get on Road Price",
      modelSlug: "amg-g-63",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 3289,
    brandName: "Maruti",
    brandSlug: "maruti",
    name: "Brezza",
    slug: "brezza",
    avgRating: 4.5,
    reviewCount: 1471,
    variantName: "Lxi CNG",
    variantSlug: "lxi-cng",
    variantPrice: "9.14 Lakh",
    minPrice: "8.19 Lakh",
    minComparePrice: 0,
    maxPrice: "14.04 Lakh",
    priceRange: "8.19 - 14.04 Lakh",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Maruti/Brezza/8679/1675859019982/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Mar 17, 2023",
    expiredAt: "Mar 17, 2046",
    isSponsored: false,
    variants: [
      {
        name: "Lxi",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "8.19 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Lxi.htm",
        variantCTAText: "Brezza Lxi",
        variantCTATitle: "Maruti Brezza Lxi",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Vxi",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "9.54 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_VXi.htm",
        variantCTAText: "Brezza Vxi",
        variantCTATitle: "Maruti Brezza Vxi",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "10.95 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi.htm",
        variantCTAText: "Brezza Zxi",
        variantCTATitle: "Maruti Brezza Zxi",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Vxi AT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "11.04 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Vxi_AT.htm",
        variantCTAText: "Brezza Vxi AT",
        variantCTATitle: "Maruti Brezza Vxi AT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi DT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "11.11 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_DT.htm",
        variantCTAText: "Brezza Zxi DT",
        variantCTATitle: "Maruti Brezza Zxi DT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi Plus",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "12.38 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_Plus.htm",
        variantCTAText: "Brezza Zxi Plus",
        variantCTATitle: "Maruti Brezza Zxi Plus",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi AT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "12.45 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_AT.htm",
        variantCTAText: "Brezza Zxi AT",
        variantCTATitle: "Maruti Brezza Zxi AT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi Plus DT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "12.54 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_Plus_DT.htm",
        variantCTAText: "Brezza Zxi Plus DT",
        variantCTATitle: "Maruti Brezza Zxi Plus DT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi AT DT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "12.61 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_AT_DT.htm",
        variantCTAText: "Brezza Zxi AT DT",
        variantCTATitle: "Maruti Brezza Zxi AT DT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi Plus AT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "13.88 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_Plus_AT.htm",
        variantCTAText: "Brezza Zxi Plus AT",
        variantCTATitle: "Maruti Brezza Zxi Plus AT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi Plus AT DT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "14.04 Lakh",
        launchedAt: "June 30, 2022",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_Plus_AT_DT.htm",
        variantCTAText: "Brezza Zxi Plus AT DT",
        variantCTATitle: "Maruti Brezza Zxi Plus AT DT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Lxi CNG",
        vehicleType: "SUV",
        fuelType: "CNG",
        price: "9.14 Lakh",
        launchedAt: "March 17, 2023",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Lxi_CNG.htm",
        variantCTAText: "Brezza Lxi CNG",
        variantCTATitle: "Maruti Brezza Lxi CNG",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Vxi CNG",
        vehicleType: "SUV",
        fuelType: "CNG",
        price: "10.49 Lakh",
        launchedAt: "March 17, 2023",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Vxi_CNG.htm",
        variantCTAText: "Brezza Vxi CNG",
        variantCTATitle: "Maruti Brezza Vxi CNG",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi CNG",
        vehicleType: "SUV",
        fuelType: "CNG",
        price: "11.89 Lakh",
        launchedAt: "March 17, 2023",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_CNG.htm",
        variantCTAText: "Brezza Zxi CNG",
        variantCTATitle: "Maruti Brezza Zxi CNG",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Zxi CNG DT",
        vehicleType: "SUV",
        fuelType: "CNG",
        price: "12.05 Lakh",
        launchedAt: "March 17, 2023",
        url: "/overview/Maruti_Brezza/Maruti_Brezza_Zxi_CNG_DT.htm",
        variantCTAText: "Brezza Zxi CNG DT",
        variantCTATitle: "Maruti Brezza Zxi CNG DT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/maruti/brezza",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Maruti/Brezza/8679/1675859019982/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Maruti Brezza",
    vehicleTypeCount: 0,
    noOfVariants: 15,
    engine: "1462 cc",
    mileage: "25.51 km/kg",
    seatingCapacity: "5 Seats",
    fuelType: "CNG",
    transmissionType: "Manual",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Maruti",
      modelName: "Maruti Brezza",
      carVariantId: "Maruti Brezza Lxi CNG",
      modelId: 3289,
      modelUrl: "/maruti/brezza",
      modelPriceURL: "/maruti/brezza/price-in-new-delhi",
      priceRnge: "5lakh-10lakh,10lakh-15lakh",
      bodyType: "SUV",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "brezza",
      dcbFormHeading: "View Personalized Offers On Maruti Brezza",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Maruti Brezza",
      cityId: "49",
      orpTitle: "Maruti Brezza On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9733",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: true,
      isDealerConnect: true,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Maruti/Brezza/8679/1675859019982/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Mar 17, 2023 12:00:00 AM",
    isVariant: false,
    gorpDto: {
      brandName: "Maruti",
      modelName: "Maruti Brezza",
      carVariantId: "Maruti Brezza Lxi CNG",
      modelUrl: "/maruti/brezza",
      modelPriceURL: "/maruti/brezza/price-in-new-delhi",
      priceRnge: "5lakh-10lakh,10lakh-15lakh",
      ctaText: "Get on Road Price",
      modelSlug: "brezza",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 3243,
    brandName: "Kia",
    brandSlug: "kia",
    name: "Carens",
    slug: "carens",
    avgRating: 4.4,
    reviewCount: 628,
    variantName: "Luxury Plus DCT",
    variantSlug: "luxury-plus-dct",
    variantPrice: "18.45 Lakh",
    minPrice: "10.45 Lakh",
    minComparePrice: 0,
    maxPrice: "18.95 Lakh",
    priceRange: "10.45 - 18.95 Lakh",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Kia/Carens/8719/1677919735002/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Mar 13, 2023",
    expiredAt: "Mar 13, 2039",
    isSponsored: false,
    variants: [
      {
        name: "Premium Diesel iMT",
        vehicleType: "MUV",
        fuelType: "Diesel",
        price: "12.65 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Premium_Diesel_iMT.htm",
        variantCTAText: "Carens Premium Diesel iMT",
        variantCTATitle: "Kia Carens Premium Diesel iMT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige Diesel iMT",
        vehicleType: "MUV",
        fuelType: "Diesel",
        price: "13.85 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Prestige_Diesel_iMT.htm",
        variantCTAText: "Carens Prestige Diesel iMT",
        variantCTATitle: "Kia Carens Prestige Diesel iMT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige Plus Diesel iMT",
        vehicleType: "MUV",
        fuelType: "Diesel",
        price: "15.35 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Prestige_Plus_Diesel_iMT.htm",
        variantCTAText: "Carens Prestige Plus Diesel iMT",
        variantCTATitle: "Kia Carens Prestige Plus Diesel iMT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Luxury Diesel iMT",
        vehicleType: "MUV",
        fuelType: "Diesel",
        price: "16.80 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Luxury_Diesel_iMT.htm",
        variantCTAText: "Carens Luxury Diesel iMT",
        variantCTATitle: "Kia Carens Luxury Diesel iMT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Luxury Plus Diesel iMT 6 STR",
        vehicleType: "MUV",
        fuelType: "Diesel",
        price: "18 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Luxury_Plus_Diesel_iMT_6_STR.htm",
        variantCTAText: "Carens Luxury Plus Diesel iMT 6 STR",
        variantCTATitle: "Kia Carens Luxury Plus Diesel iMT 6 STR",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Luxury Plus Diesel iMT",
        vehicleType: "MUV",
        fuelType: "Diesel",
        price: "18 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Luxury_Plus_Diesel_iMT.htm",
        variantCTAText: "Carens Luxury Plus Diesel iMT",
        variantCTATitle: "Kia Carens Luxury Plus Diesel iMT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige Plus DCT",
        vehicleType: "MUV",
        fuelType: "Petrol",
        price: "15.75 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Prestige_Plus_DCT.htm",
        variantCTAText: "Carens Prestige Plus DCT",
        variantCTATitle: "Kia Carens Prestige Plus DCT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Luxury Plus DCT 6 STR",
        vehicleType: "MUV",
        fuelType: "Petrol",
        price: "18.40 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Luxury_Plus_DCT_6_STR.htm",
        variantCTAText: "Carens Luxury Plus DCT 6 STR",
        variantCTATitle: "Kia Carens Luxury Plus DCT 6 STR",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Luxury Plus DCT",
        vehicleType: "MUV",
        fuelType: "Petrol",
        price: "18.45 Lakh",
        launchedAt: "March 13, 2023",
        url: "/overview/Kia_Carens/Kia_Carens_Luxury_Plus_DCT.htm",
        variantCTAText: "Carens Luxury Plus DCT",
        variantCTATitle: "Kia Carens Luxury Plus DCT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/kia/carens",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Kia/Carens/8719/1677919735002/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Kia Carens",
    vehicleTypeCount: 0,
    noOfVariants: 9,
    engine: "1482 cc",
    mileage: "",
    seatingCapacity: "7 Seats",
    fuelType: "Petrol",
    transmissionType: "Automatic",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Kia",
      modelName: "Kia Carens",
      carVariantId: "Kia Carens Luxury Plus DCT",
      modelId: 3243,
      modelUrl: "/kia/carens",
      modelPriceURL: "/kia/carens/price-in-new-delhi",
      priceRnge: "10lakh-15lakh,15lakh-20lakh",
      bodyType: "MUV",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "carens",
      dcbFormHeading: "View Personalized Offers On Kia Carens",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Kia Carens",
      cityId: "49",
      orpTitle: "Kia Carens On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9722",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: true,
      isDealerConnect: true,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Kia/Carens/8719/1677919735002/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Mar 13, 2023 12:00:00 AM",
    isVariant: false,
    gorpDto: {
      brandName: "Kia",
      modelName: "Kia Carens",
      carVariantId: "Kia Carens Luxury Plus DCT",
      modelUrl: "/kia/carens",
      modelPriceURL: "/kia/carens/price-in-new-delhi",
      priceRnge: "10lakh-15lakh,15lakh-20lakh",
      ctaText: "Get on Road Price",
      modelSlug: "carens",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 3232,
    brandName: "Hyundai",
    brandSlug: "hyundai",
    name: "Alcazar",
    slug: "alcazar",
    avgRating: 4.1,
    reviewCount: 526,
    variantName: "Platinum (O) Turbo DCT",
    variantSlug: "platinum-(o)-turbo-dct",
    variantPrice: "19.96 Lakh",
    minPrice: "16.71 Lakh",
    minComparePrice: 0,
    maxPrice: "21.10 Lakh",
    priceRange: "16.71 - 21.10 Lakh",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Alcazar/8467/1678338882534/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Mar 07, 2023",
    expiredAt: "Mar 07, 2048",
    isSponsored: false,
    variants: [
      {
        name: "Prestige 7-Seater Diesel",
        vehicleType: "SUV",
        fuelType: "Diesel",
        price: "17.71 Lakh",
        launchedAt: "February 02, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Prestige_7-Seater_Diesel.htm",
        variantCTAText: "Alcazar Prestige 7-Seater Diesel",
        variantCTATitle: "Hyundai Alcazar Prestige 7-Seater Diesel",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige 7-Seater Diesel AT",
        vehicleType: "SUV",
        fuelType: "Diesel",
        price: "19.17 Lakh",
        launchedAt: "February 02, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Prestige_7-Seater_Diesel_AT.htm",
        variantCTAText: "Alcazar Prestige 7-Seater Diesel AT",
        variantCTATitle: "Hyundai Alcazar Prestige 7-Seater Diesel AT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige Executive 7-Seater Diesel",
        vehicleType: "SUV",
        fuelType: "Diesel",
        price: "16.71 Lakh",
        launchedAt: "July 06, 2022",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Prestige_Executive_7-Seater_Diesel.htm",
        variantCTAText: "Alcazar Prestige Executive 7-Seater Diesel",
        variantCTATitle: "Hyundai Alcazar Prestige Executive 7-Seater Diesel",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige Executive Diesel",
        vehicleType: "SUV",
        fuelType: "Diesel",
        price: "16.71 Lakh",
        launchedAt: "July 06, 2022",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Prestige_Executive_Diesel.htm",
        variantCTAText: "Alcazar Prestige Executive Diesel",
        variantCTATitle: "Hyundai Alcazar Prestige Executive Diesel",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige Executive 7-Seater Diesel AT",
        vehicleType: "SUV",
        fuelType: "Diesel",
        price: "18.18 Lakh",
        launchedAt: "July 06, 2022",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Prestige_Executive_7-Seater_Diesel_AT.htm",
        variantCTAText: "Alcazar Prestige Executive 7-Seater Diesel AT",
        variantCTATitle:
          "Hyundai Alcazar Prestige Executive 7-Seater Diesel AT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Prestige Turbo 7 Seater",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "16.75 Lakh",
        launchedAt: "March 07, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Prestige_Turbo_7_Seater.htm",
        variantCTAText: "Alcazar Prestige Turbo 7 Seater",
        variantCTATitle: "Hyundai Alcazar Prestige Turbo 7 Seater",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Platinum Turbo 7 Seater",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "18.65 Lakh",
        launchedAt: "March 07, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Platinum_Turbo_7_Seater.htm",
        variantCTAText: "Alcazar Platinum Turbo 7 Seater",
        variantCTATitle: "Hyundai Alcazar Platinum Turbo 7 Seater",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: true,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Platinum (O) Turbo DCT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "19.96 Lakh",
        launchedAt: "March 07, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Platinum_(O)_Turbo_DCT.htm",
        variantCTAText: "Alcazar Platinum (O) Turbo DCT",
        variantCTATitle: "Hyundai Alcazar Platinum (O) Turbo DCT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Platinum (O) Turbo DCT 7 Seater",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "19.96 Lakh",
        launchedAt: "March 07, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Platinum_(O)_Turbo_DCT_7_Seater.htm",
        variantCTAText: "Alcazar Platinum (O) Turbo DCT 7 Seater",
        variantCTATitle: "Hyundai Alcazar Platinum (O) Turbo DCT 7 Seater",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Signature (O) Turbo DCT 7 Seater",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "20.25 Lakh",
        launchedAt: "March 07, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Signature_(O)_Turbo_DCT_7_Seater.htm",
        variantCTAText: "Alcazar Signature (O) Turbo DCT 7 Seater",
        variantCTATitle: "Hyundai Alcazar Signature (O) Turbo DCT 7 Seater",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Signature (O) Turbo DCT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "20.25 Lakh",
        launchedAt: "February 07, 2023",
        url:
          "/overview/Hyundai_Alcazar/Hyundai_Alcazar_Signature_(O)_Turbo_DCT.htm",
        variantCTAText: "Alcazar Signature (O) Turbo DCT",
        variantCTATitle: "Hyundai Alcazar Signature (O) Turbo DCT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/hyundai/alcazar",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Alcazar/8467/1678338882534/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Hyundai Alcazar",
    vehicleTypeCount: 0,
    noOfVariants: 11,
    engine: "1482 cc",
    mileage: "",
    seatingCapacity: "6 Seats",
    fuelType: "Petrol",
    transmissionType: "Automatic",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Hyundai",
      modelName: "Hyundai Alcazar",
      carVariantId: "Hyundai Alcazar Platinum (O) Turbo DCT",
      modelId: 3232,
      modelUrl: "/hyundai/alcazar",
      modelPriceURL: "/hyundai/alcazar/price-in-new-delhi",
      priceRnge: "15lakh-20lakh,20lakh-50lakh",
      bodyType: "SUV",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "alcazar",
      dcbFormHeading: "View Personalized Offers On Hyundai Alcazar",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Hyundai Alcazar",
      cityId: "49",
      orpTitle: "Hyundai Alcazar On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9719",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: true,
      isDealerConnect: true,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Hyundai/Alcazar/8467/1678338882534/front-left-side-47.jpg",
      emailIdRequired: "1",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Mar 7, 2023 12:00:00 AM",
    isVariant: false,
    gorpDto: {
      brandName: "Hyundai",
      modelName: "Hyundai Alcazar",
      carVariantId: "Hyundai Alcazar Platinum (O) Turbo DCT",
      modelUrl: "/hyundai/alcazar",
      modelPriceURL: "/hyundai/alcazar/price-in-new-delhi",
      priceRnge: "15lakh-20lakh,20lakh-50lakh",
      ctaText: "Get on Road Price",
      modelSlug: "alcazar",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 3206,
    brandName: "Mercedes-Benz",
    brandSlug: "mercedes-benz",
    name: "S-Class",
    slug: "s-class",
    avgRating: 4.7,
    reviewCount: 47,
    variantName: "S400d 4Matic",
    variantSlug: "s400d-4matic",
    variantPrice: "2.17 Cr",
    minPrice: "1.65 Cr",
    minComparePrice: 0,
    maxPrice: "2.17 Cr",
    priceRange: "1.65 - 2.17 Cr",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mercedes-Benz/S-Class/7994/1633596468711/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Mar 06, 2023",
    expiredAt: "Oct 07, 2029",
    isSponsored: false,
    variants: [
      {
        name: "S400d 4Matic",
        vehicleType: "Sedans",
        fuelType: "Diesel",
        price: "2.17 Cr",
        launchedAt: "March 06, 2023",
        url:
          "/overview/Mercedes-Benz_S-Class/Mercedes-Benz_S-Class_S400d_4Matic.htm",
        variantCTAText: "S-Class S400d 4Matic",
        variantCTATitle: "Mercedes-Benz S-Class S400d 4Matic",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/mercedes-benz/s-class",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mercedes-Benz/S-Class/7994/1633596468711/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Mercedes-Benz S-Class",
    vehicleTypeCount: 0,
    noOfVariants: 1,
    engine: "2925 cc",
    mileage: "13.38 kmpl",
    seatingCapacity: "5 Seats",
    fuelType: "Diesel",
    transmissionType: "Automatic",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Mercedes-Benz",
      modelName: "Mercedes-Benz S-Class",
      carVariantId: "Mercedes-Benz S-Class S400d 4Matic",
      modelId: 3206,
      modelUrl: "/mercedes-benz/s-class",
      modelPriceURL: "/mercedes-benz/s-class/price-in-new-delhi",
      priceRnge: "1+crore",
      bodyType: "Sedans",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "s-class",
      dcbFormHeading: "View Personalized Offers On Mercedes-Benz S-Class",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Mercedes-Benz S-Class",
      cityId: "49",
      orpTitle: "Mercedes-Benz S-Class On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "8181",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: false,
      isDealerConnect: false,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mercedes-Benz/S-Class/7994/1633596468711/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Mar 6, 2023 1:00:00 PM",
    isVariant: false,
    cardIconTagList: [
      {
        text: "Facelift",
        defaultKey: false,
        brandId: 0,
        keyFeatureAvailable: false,
        showRs: false,
        iconClass: "icon-facelift",
        rightFlag: true,
        minPriceRange: 0,
        maxPriceRange: 0,
        isNctFilterOn: false,
        showFillButton: false
      }
    ],
    gorpDto: {
      brandName: "Mercedes-Benz",
      modelName: "Mercedes-Benz S-Class",
      carVariantId: "Mercedes-Benz S-Class S400d 4Matic",
      modelUrl: "/mercedes-benz/s-class",
      modelPriceURL: "/mercedes-benz/s-class/price-in-new-delhi",
      priceRnge: "1+crore",
      ctaText: "Get on Road Price",
      modelSlug: "s-class",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 649,
    brandName: "Porsche",
    brandSlug: "porsche",
    name: "Cayenne",
    slug: "cayenne",
    avgRating: 4.8,
    reviewCount: 23,
    variantName: "Turbo GT",
    variantSlug: "turbo-gt",
    variantPrice: "2.57 Cr",
    minPrice: "1.27 Cr",
    minComparePrice: 0,
    maxPrice: "2.57 Cr",
    priceRange: "1.27 - 2.57 Cr",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Porsche/Cayenne/4467/1677651641375/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Jan 20, 2023",
    expiredAt: "Jan 20, 2040",
    isSponsored: false,
    variants: [
      {
        name: "Turbo GT",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "2.57 Cr",
        launchedAt: "January 20, 2023",
        url: "/overview/Porsche_Cayenne/Porsche_Cayenne_Turbo_GT.htm",
        variantCTAText: "Cayenne Turbo GT",
        variantCTATitle: "Porsche Cayenne Turbo GT",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Platinum Edition",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "1.47 Cr",
        launchedAt: "January 20, 2023",
        url: "/overview/Porsche_Cayenne/Porsche_Cayenne_Platinum_Edition.htm",
        variantCTAText: "Cayenne Platinum Edition",
        variantCTATitle: "Porsche Cayenne Platinum Edition",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "E-Hybrid Platinum Edition",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "1.89 Cr",
        launchedAt: "April 26, 2022",
        url:
          "/overview/Porsche_Cayenne/Porsche_Cayenne_E-Hybrid_Platinum_Edition.htm",
        variantCTAText: "Cayenne E-Hybrid Platinum Edition",
        variantCTATitle: "Porsche Cayenne E-Hybrid Platinum Edition",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/carmodels/Porsche/Porsche_Cayenne",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Porsche/Cayenne/4467/1677651641375/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Porsche Cayenne",
    vehicleTypeCount: 0,
    noOfVariants: 3,
    engine: "3996 cc",
    mileage: "",
    seatingCapacity: "5 Seats",
    fuelType: "Petrol",
    transmissionType: "Automatic",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Porsche",
      modelName: "Porsche Cayenne",
      carVariantId: "Porsche Cayenne Turbo GT",
      modelId: 649,
      modelUrl: "/carmodels/Porsche/Porsche_Cayenne",
      modelPriceURL: "/porsche-cayenne/car-price-in-new-delhi.htm",
      priceRnge: "1+crore",
      bodyType: "SUV",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "cayenne",
      dcbFormHeading: "View Personalized Offers On Porsche Cayenne",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Porsche Cayenne",
      cityId: "49",
      orpTitle: "Porsche Cayenne On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9591",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: false,
      isDealerConnect: false,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Porsche/Cayenne/4467/1677651641375/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Jan 20, 2023 4:00:00 PM",
    isVariant: false,
    gorpDto: {
      brandName: "Porsche",
      modelName: "Porsche Cayenne",
      carVariantId: "Porsche Cayenne Turbo GT",
      modelUrl: "/carmodels/Porsche/Porsche_Cayenne",
      modelPriceURL: "/porsche-cayenne/car-price-in-new-delhi.htm",
      priceRnge: "1+crore",
      ctaText: "Get on Road Price",
      modelSlug: "cayenne",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 3112,
    brandName: "Porsche",
    brandSlug: "porsche",
    name: "Taycan",
    slug: "taycan",
    avgRating: 4.4,
    reviewCount: 57,
    variantName: "GTS",
    variantSlug: "gts",
    variantPrice: "1.95 Cr",
    minPrice: "1.53 Cr",
    minComparePrice: 0,
    maxPrice: "2.34 Cr",
    priceRange: "1.53 - 2.34 Cr",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Porsche/Taycan/7041/1636711367887/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Jan 20, 2023",
    expiredAt: "Jan 20, 2048",
    isSponsored: false,
    variants: [
      {
        name: "GTS",
        vehicleType: "Wagons",
        fuelType: "Electric",
        price: "1.95 Cr",
        launchedAt: "January 20, 2023",
        url: "/overview/Porsche_Taycan/Porsche_Taycan_GTS.htm",
        variantCTAText: "Taycan GTS",
        variantCTATitle: "Porsche Taycan GTS",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "4S",
        vehicleType: "Wagons",
        fuelType: "Electric",
        price: "1.67 Cr",
        launchedAt: "April 27, 2022",
        url: "/overview/Porsche_Taycan/Porsche_Taycan_4S.htm",
        variantCTAText: "Taycan 4S",
        variantCTATitle: "Porsche Taycan 4S",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Turbo",
        vehicleType: "Wagons",
        fuelType: "Electric",
        price: "2.12 Cr",
        launchedAt: "April 27, 2022",
        url: "/overview/Porsche_Taycan/Porsche_Taycan_Turbo.htm",
        variantCTAText: "Taycan Turbo",
        variantCTATitle: "Porsche Taycan Turbo",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      },
      {
        name: "Turbo S",
        vehicleType: "Wagons",
        fuelType: "Electric",
        price: "2.34 Cr",
        launchedAt: "April 27, 2022",
        url: "/overview/Porsche_Taycan/Porsche_Taycan_Turbo_S.htm",
        variantCTAText: "Taycan Turbo S",
        variantCTATitle: "Porsche Taycan Turbo S",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/porsche/taycan",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Porsche/Taycan/7041/1636711367887/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Porsche Taycan",
    vehicleTypeCount: 0,
    noOfVariants: 4,
    mileage: "",
    seatingCapacity: "5 Seats",
    fuelType: "Electric",
    transmissionType: "Automatic",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Porsche",
      modelName: "Porsche Taycan",
      carVariantId: "Porsche Taycan GTS",
      modelId: 3112,
      modelUrl: "/porsche/taycan",
      modelPriceURL: "/porsche/taycan/price-in-new-delhi",
      priceRnge: "1+crore",
      bodyType: "Wagons",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "taycan",
      dcbFormHeading: "View Personalized Offers On Porsche Taycan",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Porsche Taycan",
      cityId: "49",
      orpTitle: "Porsche Taycan On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9593",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: false,
      isDealerConnect: false,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Porsche/Taycan/7041/1636711367887/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Jan 20, 2023 4:00:00 PM",
    isVariant: false,
    cardIconTagList: [
      {
        text: "Electric",
        defaultKey: false,
        brandId: 0,
        keyFeatureAvailable: false,
        showRs: false,
        iconClass: "icon-electricNew",
        rightFlag: false,
        minPriceRange: 0,
        maxPriceRange: 0,
        isNctFilterOn: false,
        showFillButton: false
      }
    ],
    gorpDto: {
      brandName: "Porsche",
      modelName: "Porsche Taycan",
      carVariantId: "Porsche Taycan GTS",
      modelUrl: "/porsche/taycan",
      modelPriceURL: "/porsche/taycan/price-in-new-delhi",
      priceRnge: "1+crore",
      ctaText: "Get on Road Price",
      modelSlug: "taycan",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  },
  {
    id: 3413,
    brandName: "Bentley",
    brandSlug: "bentley",
    name: "Bentayga EWB",
    slug: "bentayga-ewb",
    avgRating: 0,
    variantName: "Azure",
    variantSlug: "azure",
    variantPrice: "6 Cr",
    minPrice: "6 Cr",
    minComparePrice: 0,
    maxPrice: "6 Cr",
    priceRange: "6 Cr",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Bentley/Bentayga-EWB/9587/1674274188746/front-left-side-47.jpg",
    status: "Active",
    launchedAt: "Jan 20, 2023",
    expiredAt: "Jan 20, 2048",
    isSponsored: false,
    variants: [
      {
        name: "Azure",
        vehicleType: "SUV",
        fuelType: "Petrol",
        price: "6 Cr",
        launchedAt: "January 20, 2023",
        url: "/overview/Bentley_Bentayga_EWB/Bentley_Bentayga_EWB_Azure.htm",
        variantCTAText: "Bentayga EWB Azure",
        variantCTATitle: "Bentley Bentayga EWB Azure",
        centralid: 0,
        inventoryId: 0,
        modelId: 0,
        topSelling: false,
        paymentRequired: false,
        demoCar: false,
        year: 0,
        kilometer: 0,
        isVerifiedDeal: false,
        discountMoney: 0,
        stockCount: 0,
        payAmount: 0,
        exchangeDiscount: 0,
        financeDiscount: 0,
        corporateDiscount: 0
      }
    ],
    modelUrl: "/bentley/bentayga-ewb",
    webpImage:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Bentley/Bentayga-EWB/9587/1674274188746/front-left-side-47.webp",
    modelPopularity: 0,
    modelName: "Bentley Bentayga EWB",
    vehicleTypeCount: 0,
    noOfVariants: 1,
    engine: "3998 cc",
    mileage: "",
    seatingCapacity: "5 Seats",
    fuelType: "Petrol",
    transmissionType: "Automatic",
    generateORPLead: 0,
    dcbdto: {
      brandName: "Bentley",
      modelName: "Bentley Bentayga EWB",
      carVariantId: "Bentley Bentayga EWB Azure",
      modelId: 3413,
      modelUrl: "/bentley/bentayga-ewb",
      modelPriceURL: "/bentley/bentayga-ewb/price-in-new-delhi",
      priceRnge: "1+crore",
      bodyType: "SUV",
      leadButton: 0,
      ctaText: "Check March Offer",
      modelSlug: "bentayga-ewb",
      dcbFormHeading: "View Personalized Offers On Bentley Bentayga EWB",
      delightImage:
        "https://stimg.cardekho.com/images/uploadimages/1574416509358/Desktop-Banner.png",
      delightImageMobi:
        "https://stimg.cardekho.com/images/uploadimages/1575477186270/BANNER.png",
      modelDisplayName: "Bentley Bentayga EWB",
      cityId: "49",
      orpTitle: "Bentley Bentayga EWB On Road Price in New Delhi",
      verificationBytruecaller: true,
      showDirectDealerCall: false,
      carVariantCentralId: "9587",
      displayCtaText: "Check March Offers",
      apiOptions: {
        secondaryCTA: false,
        mlCTA: false,
        isLdCta: false,
        isServiceCenterLead: false,
        isAckoLead: false
      },
      dcCtaText: "REQUEST A CALLBACK",
      withDCCall: false,
      isDealerConnect: false,
      subTitle: "We only ask these once and your details are safe with us.",
      leadTypeCode: 70,
      isOCBFlow: false,
      modelImage:
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Bentley/Bentayga-EWB/9587/1674274188746/front-left-side-47.jpg",
      emailIdRequired: "0",
      generateORPLead: 0
    },
    openInNewTab: 0,
    modelStatus: "CURRENT",
    linkViaClick: false,
    dealerListActivated: false,
    startDate: "Jan 20, 2023 12:00:00 AM",
    isVariant: false,
    gorpDto: {
      brandName: "Bentley",
      modelName: "Bentley Bentayga EWB",
      carVariantId: "Bentley Bentayga EWB Azure",
      modelUrl: "/bentley/bentayga-ewb",
      modelPriceURL: "/bentley/bentayga-ewb/price-in-new-delhi",
      priceRnge: "1+crore",
      ctaText: "Get on Road Price",
      modelSlug: "bentayga-ewb",
      displayCtaText: "Get on Road Price",
      generateORPLead: 0
    },
    rating: 0,
    showOfferTag: false,
    showFillButton: false,
    isFtc: false,
    defaultKey: false
  }
];
export default function Sixth() {
  return (
    <div className="Sixth">
      <h1>Cars Details</h1>
      <ul>
        {cars.map((ele) => (
          <li key={ele.id} id={ele.id}>
            {ele.name} is of brand {ele.brandName} and costs for amount between{" "}
            {ele.priceRange}
          </li>
        ))}
      </ul>
      <hr />
    </div>
  );
}
